language: rust
os:
  - osx
  - linux
rust:
  - stable
  - beta
  - nightly
script:
  - RUSTFLAGS='-F warnings' cargo build --verbose --all
  - RUSTFLAGS='-F warnings' cargo test --verbose --all
stages:
  - Check
  - Test
  - Deploy
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      script:
        - rustup component add clippy
        - RUSTFLAGS='-F warnings' cargo clippy --all --all-targets --all-features
    - stage: Deploy
      if: branch = master
      name: Deploy
      script:
        - cargo clean
        - cargo publish --token "${CARGO_PUBLISH_TOKEN}" && echo "Publish is DONE." || echo "Failed to publish."
